### ISSUE TITLE
No indication on requirements of serial hardware/software for Arduino device

### ISSUE THREAD

**Issue by OwenBrotherwood** [TheThingsNetwork/arduino-node-lib#1]
Hi Guys
I just spent a nice day with several successes: then I tried "this".

Context:
"We" are trying to create a http://makecode.com solution for TTN for kids and needed a known setup to go thru GW (Pi : as a newbi), Device and the setup required to get a device working within the bounds of a quick test with TTN console pages: I got there thanks to some help from Gonzalos and Lorenz (his shield).

The next step was to do a Cayenne setup: I got some good info from cdro and found the necessary repos.
Then I hit `#define loraSerial Serial1`: some googling and something to do with SW and HW Serial.

As stated, I want to get the makecode devices onto TTN, and I don't have arduino, so I had borrowed an arduino uno R3 which seems to not support the requirements for hardware for this library

Summary:
Some statement of requirement for the arduino such that the ardunio chosen fits the code

My 5 cents :)

**Comment by johanstokking** [comment]
Thanks. This library is specific for The Things Node. I'm assuming that you're using `TheThingsNetwork` library, which is in https://github.com/TheThingsNetwork/arduino-device-lib. I'll file an issue there.
