### ISSUE TITLE
The Things Node :: Basic Example :: Problem with negative temperatures ..

### ISSUE THREAD

**Issue by PreinfalkG** [TheThingsNetwork/arduino-node-lib#24]
In the [basic example](https://github.com/TheThingsNetwork/arduino-node-lib/tree/master/examples/Basic) **negative temperatures** are not processed correctly -> see Screenshot

![2020-01-07_TheThingsNode-BasicExample](https://user-images.githubusercontent.com/16906959/71884304-54de3600-3138-11ea-90d4-39719080b9db.png)

**Comment by johanstokking** [comment]
I cannot reproduce:

```
$ node
Welcome to Node.js v12.12.0.
Type ".help" for more information.
> let bytes = [0, 0, 0, 0, 0xfe, 0xc1]
undefined
> let decoded = {}
undefined
> decoded.temperature = ((0xffff << 16) + (bytes[4] << 8) + bytes[5]) / 100;
-3.19
```

Are you sure you are using the most up-to-date `Decoder.js` from the example you referenced?

**Comment by PreinfalkG** [comment]
oh sorry, i really used an old version of decoder.js
